
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

class CustomThemeData {
  static final lightTheme = FlexThemeData.light(
  colors: const FlexSchemeColor(
  primary: Color(0xff1145a4),
  primaryContainer: Color(0xffacc7f6),
  secondary: Color(0xffb61d1d),
  secondaryContainer: Color(0xffec9f9f),
  tertiary: Color(0xff376bca),
  tertiaryContainer: Color(0xffcfdbf2),
  appBarColor: Color(0xffcfdbf2),
  error: Color(0xffb00020),
  ),
  appBarStyle: FlexAppBarStyle.primary,
  appBarElevation: 4.0,
  bottomAppBarElevation: 8.0,
  tabBarStyle: FlexTabBarStyle.forAppBar,
  subThemesData: const FlexSubThemesData(
  interactionEffects: false,
  tintedDisabledControls: false,
  blendOnColors: false,
  useTextTheme: true,
  useM2StyleDividerInM3: true,
  adaptiveRemoveElevationTint: FlexAdaptive.all(),
  adaptiveElevationShadowsBack: FlexAdaptive.all(),
  adaptiveAppBarScrollUnderOff: FlexAdaptive.all(),
  defaultRadius: 4.0,
  elevatedButtonSchemeColor: SchemeColor.onPrimary,
  elevatedButtonSecondarySchemeColor: SchemeColor.primary,
  inputDecoratorSchemeColor: SchemeColor.onSurface,
  inputDecoratorBackgroundAlpha: 13,
  inputDecoratorBorderSchemeColor: SchemeColor.primary,
  inputDecoratorUnfocusedBorderIsColored: false,
  fabUseShape: true,
  fabAlwaysCircular: true,
  chipSchemeColor: SchemeColor.primary,
  chipRadius: 20.0,
  popupMenuElevation: 8.0,
  alignedDropdown: true,
  tooltipRadius: 4,
  dialogElevation: 24.0,
  useInputDecoratorThemeInDialogs: true,
  datePickerHeaderBackgroundSchemeColor: SchemeColor.primary,
  snackBarBackgroundSchemeColor: SchemeColor.inverseSurface,
  appBarScrolledUnderElevation: 4.0,
  tabBarIndicatorSize: TabBarIndicatorSize.tab,
  tabBarIndicatorWeight: 2,
  tabBarIndicatorTopRadius: 0,
  tabBarDividerColor: Color(0x00000000),
  drawerElevation: 16.0,
  drawerWidth: 304.0,
  bottomSheetElevation: 10.0,
  bottomSheetModalElevation: 20.0,
  bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
  bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
  bottomNavigationBarElevation: 8.0,
  menuElevation: 8.0,
  menuBarRadius: 0.0,
  menuBarElevation: 1.0,
  navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
  navigationBarUnselectedLabelSchemeColor: SchemeColor.onSurface,
  navigationBarSelectedIconSchemeColor: SchemeColor.onSurface,
  navigationBarUnselectedIconSchemeColor: SchemeColor.onSurface,
  navigationBarIndicatorSchemeColor: SchemeColor.secondary,
  navigationBarBackgroundSchemeColor: SchemeColor.surfaceVariant,
  navigationBarElevation: 0.0,
  navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
  navigationRailUnselectedLabelSchemeColor: SchemeColor.onSurface,
  navigationRailSelectedIconSchemeColor: SchemeColor.onSurface,
  navigationRailUnselectedIconSchemeColor: SchemeColor.onSurface,
  navigationRailIndicatorSchemeColor: SchemeColor.secondary,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  );
  // To use the Playground font, add GoogleFonts package and uncomment
  // fontFamily: GoogleFonts.notoSans().fontFamily,

}

